declare module "exif-reader" {
  // Generated from tags.js, https://exiftool.org/TagNames/EXIF.html and https://exiv2.org/tags.html
  // tags.js defines the same tag name for multiple tags, e.g. the name `WhiteBalance` is
  // defined for 0xA403 (number) and 0xFE4E (string). If both tags are present,
  // the later will overwrite the former making typing difficult.

  export type ExifTagName =
    | "InteropIndex"
    | "InteropVersion"
    | "ProcessingSoftware"
    | "SubfileType"
    | "OldSubfileType"
    | "ImageWidth"
    | "ImageHeight"
    | "BitsPerSample"
    | "Compression"
    | "PhotometricInterpretation"
    | "Thresholding"
    | "CellWidth"
    | "CellLength"
    | "FillOrder"
    | "DocumentName"
    | "ImageDescription"
    | "Make"
    | "Model"
    | "StripOffsets"
    | "Orientation"
    | "SamplesPerPixel"
    | "RowsPerStrip"
    | "StripByteCounts"
    | "MinSampleValue"
    | "MaxSampleValue"
    | "XResolution"
    | "YResolution"
    | "PlanarConfiguration"
    | "PageName"
    | "XPosition"
    | "YPosition"
    | "FreeOffsets"
    | "FreeByteCounts"
    | "GrayResponseUnit"
    | "GrayResponseCurve"
    | "T4Options"
    | "T6Options"
    | "ResolutionUnit"
    | "PageNumber"
    | "ColorResponseUnit"
    | "TransferFunction"
    | "Software"
    | "Artist"
    | "HostComputer"
    | "Predictor"
    | "WhitePoint"
    | "PrimaryChromaticities"
    | "ColorMap"
    | "HalftoneHints"
    | "TileWidth"
    | "TileLength"
    | "TileOffsets"
    | "TileByteCounts"
    | "BadFaxLines"
    | "CleanFaxData"
    | "ConsecutiveBadFaxLines"
    | "SubIFD"
    | "InkSet"
    | "InkNames"
    | "NumberofInks"
    | "DotRange"
    | "TargetPrinter"
    | "ExtraSamples"
    | "SampleFormat"
    | "SMinSampleValue"
    | "SMaxSampleValue"
    | "TransferRange"
    | "ClipPath"
    | "XClipPathUnits"
    | "YClipPathUnits"
    | "Indexed"
    | "JPEGTables"
    | "OPIProxy"
    | "GlobalParametersIFD"
    | "ProfileType"
    | "FaxProfile"
    | "CodingMethods"
    | "VersionYear"
    | "ModeNumber"
    | "Decode"
    | "DefaultImageColor"
    | "T82Options"
    | "JPEGProc"
    | "ThumbnailOffset"
    | "ThumbnailLength"
    | "JPEGRestartInterval"
    | "JPEGLosslessPredictors"
    | "JPEGPointTransforms"
    | "JPEGQTables"
    | "JPEGDCTables"
    | "JPEGACTables"
    | "YCbCrCoefficients"
    | "YCbCrSubSampling"
    | "YCbCrPositioning"
    | "ReferenceBlackWhite"
    | "StripRowCounts"
    | "ApplicationNotes"
    | "USPTOMiscellaneous"
    | "RelatedImageFileFormat"
    | "RelatedImageWidth"
    | "RelatedImageHeight"
    | "Rating"
    | "XP_DIP_XML"
    | "StitchInfo"
    | "RatingPercent"
    | "ImageID"
    | "WangTag1"
    | "WangAnnotation"
    | "WangTag3"
    | "WangTag4"
    | "Matteing"
    | "DataType"
    | "ImageDepth"
    | "TileDepth"
    | "Model2"
    | "CFARepeatPatternDim"
    | "CFAPattern2"
    | "BatteryLevel"
    | "KodakIFD"
    | "Copyright"
    | "ExposureTime"
    | "FNumber"
    | "MDFileTag"
    | "MDScalePixel"
    | "MDColorTable"
    | "MDLabName"
    | "MDSampleInfo"
    | "MDPrepDate"
    | "MDPrepTime"
    | "MDFileUnits"
    | "PixelScale"
    | "AdventScale"
    | "AdventRevision"
    | "UIC1Tag"
    | "UIC2Tag"
    | "UIC3Tag"
    | "UIC4Tag"
    | "IPTC-NAA"
    | "IntergraphPacketData"
    | "IntergraphFlagRegisters"
    | "IntergraphMatrix"
    | "INGRReserved"
    | "ModelTiePoint"
    | "Site"
    | "ColorSequence"
    | "IT8Header"
    | "RasterPadding"
    | "BitsPerRunLength"
    | "BitsPerExtendedRunLength"
    | "ColorTable"
    | "ImageColorIndicator"
    | "BackgroundColorIndicator"
    | "ImageColorValue"
    | "BackgroundColorValue"
    | "PixelIntensityRange"
    | "TransparencyIndicator"
    | "ColorCharacterization"
    | "HCUsage"
    | "TrapIndicator"
    | "CMYKEquivalent"
    | "SEMInfo"
    | "AFCP_IPTC"
    | "PixelMagicJBIGOptions"
    | "ModelTransform"
    | "WB_GRGBLevels"
    | "LeafData"
    | "PhotoshopSettings"
    | "ICC_Profile"
    | "TIFF_FXExtensions"
    | "MultiProfiles"
    | "SharedData"
    | "T88Options"
    | "ImageLayer"
    | "GeoTiffDirectory"
    | "GeoTiffDoubleParams"
    | "GeoTiffAsciiParams"
    | "ExposureProgram"
    | "SpectralSensitivity"
    | "ISO"
    | "Opto-ElectricConvFactor"
    | "Interlace"
    | "TimeZoneOffset"
    | "SelfTimerMode"
    | "SensitivityType"
    | "StandardOutputSensitivity"
    | "RecommendedExposureIndex"
    | "ISOSpeed"
    | "ISOSpeedLatitudeyyy"
    | "ISOSpeedLatitudezzz"
    | "FaxRecvParams"
    | "FaxSubAddress"
    | "FaxRecvTime"
    | "LeafSubIFD"
    | "ExifVersion"
    | "ComponentsConfiguration"
    | "CompressedBitsPerPixel"
    | "ShutterSpeedValue"
    | "ApertureValue"
    | "BrightnessValue"
    | "ExposureBiasValue"
    | "MaxApertureValue"
    | "SubjectDistance"
    | "MeteringMode"
    | "LightSource"
    | "Flash"
    | "FocalLength"
    | "FlashEnergy"
    | "SpatialFrequencyResponse"
    | "Noise"
    | "FocalPlaneXResolution"
    | "FocalPlaneYResolution"
    | "FocalPlaneResolutionUnit"
    | "ImageNumber"
    | "SecurityClassification"
    | "ImageHistory"
    | "SubjectArea"
    | "ExposureIndex"
    | "TIFF-EPStandardID"
    | "SensingMethod"
    | "CIP3DataFile"
    | "CIP3Sheet"
    | "CIP3Side"
    | "StoNits"
    | "MakerNote"
    | "UserComment"
    | "SubSecTime"
    | "SubSecTimeOriginal"
    | "SubSecTimeDigitized"
    | "MSDocumentText"
    | "MSPropertySetStorage"
    | "MSDocumentTextPosition"
    | "ImageSourceData"
    | "XPTitle"
    | "XPComment"
    | "XPAuthor"
    | "XPKeywords"
    | "XPSubject"
    | "FlashpixVersion"
    | "ColorSpace"
    | "PixelXDimension"
    | "PixelYDimension"
    | "RelatedSoundFile"
    | "SubjectLocation"
    | "FileSource"
    | "SceneType"
    | "CFAPattern"
    | "CustomRendered"
    | "ExposureMode"
    | "WhiteBalance"
    | "DigitalZoomRatio"
    | "FocalLengthIn35mmFormat"
    | "SceneCaptureType"
    | "GainControl"
    | "Contrast"
    | "Saturation"
    | "Sharpness"
    | "DeviceSettingDescription"
    | "SubjectDistanceRange"
    | "ImageUniqueID"
    | "CameraOwnerName"
    | "BodySerialNumber"
    | "LensSpecification"
    | "LensMake"
    | "LensModel"
    | "LensSerialNumber"
    | "GDALMetadata"
    | "GDALNoData"
    | "Gamma"
    | "ExpandSoftware"
    | "ExpandLens"
    | "ExpandFilm"
    | "ExpandFilterLens"
    | "ExpandScanner"
    | "ExpandFlashLamp"
    | "PixelFormat"
    | "Transformation"
    | "Uncompressed"
    | "ImageType"
    | "WidthResolution"
    | "HeightResolution"
    | "ImageOffset"
    | "ImageByteCount"
    | "AlphaOffset"
    | "AlphaByteCount"
    | "ImageDataDiscard"
    | "AlphaDataDiscard"
    | "OceScanjobDesc"
    | "OceApplicationSelector"
    | "OceIDNumber"
    | "OceImageLogic"
    | "Annotations"
    | "PrintIM"
    | "USPTOOriginalContentType"
    | "DNGVersion"
    | "DNGBackwardVersion"
    | "UniqueCameraModel"
    | "LocalizedCameraModel"
    | "CFAPlaneColor"
    | "CFALayout"
    | "LinearizationTable"
    | "BlackLevelRepeatDim"
    | "BlackLevel"
    | "BlackLevelDeltaH"
    | "BlackLevelDeltaV"
    | "WhiteLevel"
    | "DefaultScale"
    | "DefaultCropOrigin"
    | "DefaultCropSize"
    | "ColorMatrix1"
    | "ColorMatrix2"
    | "CameraCalibration1"
    | "CameraCalibration2"
    | "ReductionMatrix1"
    | "ReductionMatrix2"
    | "AnalogBalance"
    | "AsShotNeutral"
    | "AsShotWhiteXY"
    | "BaselineExposure"
    | "BaselineNoise"
    | "BaselineSharpness"
    | "BayerGreenSplit"
    | "LinearResponseLimit"
    | "CameraSerialNumber"
    | "DNGLensInfo"
    | "ChromaBlurRadius"
    | "AntiAliasStrength"
    | "ShadowScale"
    | "DNGPrivateData"
    | "MakerNoteSafety"
    | "RawImageSegmentation"
    | "CalibrationIlluminant1"
    | "CalibrationIlluminant2"
    | "BestQualityScale"
    | "RawDataUniqueID"
    | "AliasLayerMetadata"
    | "OriginalRawFileName"
    | "OriginalRawFileData"
    | "ActiveArea"
    | "MaskedAreas"
    | "AsShotICCProfile"
    | "AsShotPreProfileMatrix"
    | "CurrentICCProfile"
    | "CurrentPreProfileMatrix"
    | "ColorimetricReference"
    | "PanasonicTitle"
    | "PanasonicTitle2"
    | "CameraCalibrationSig"
    | "ProfileCalibrationSig"
    | "ProfileIFD"
    | "AsShotProfileName"
    | "NoiseReductionApplied"
    | "ProfileName"
    | "ProfileHueSatMapDims"
    | "ProfileHueSatMapData1"
    | "ProfileHueSatMapData2"
    | "ProfileToneCurve"
    | "ProfileEmbedPolicy"
    | "ProfileCopyright"
    | "ForwardMatrix1"
    | "ForwardMatrix2"
    | "PreviewApplicationName"
    | "PreviewApplicationVersion"
    | "PreviewSettingsName"
    | "PreviewSettingsDigest"
    | "PreviewColorSpace"
    | "PreviewDateTime"
    | "RawImageDigest"
    | "OriginalRawFileDigest"
    | "SubTileBlockSize"
    | "RowInterleaveFactor"
    | "ProfileLookTableDims"
    | "ProfileLookTableData"
    | "OpcodeList1"
    | "OpcodeList2"
    | "OpcodeList3"
    | "NoiseProfile"
    | "TimeCodes"
    | "FrameRate"
    | "TStop"
    | "ReelName"
    | "OriginalDefaultFinalSize"
    | "OriginalBestQualitySize"
    | "OriginalDefaultCropSize"
    | "CameraLabel"
    | "ProfileHueSatMapEncoding"
    | "ProfileLookTableEncoding"
    | "BaselineExposureOffset"
    | "DefaultBlackRender"
    | "NewRawImageDigest"
    | "RawToPreviewGain"
    | "DefaultUserCrop"
    | "Padding"
    | "OffsetSchema"
    | "OwnerName"
    | "SerialNumber"
    | "Lens"
    | "KDC_IFD"
    | "RawFile"
    | "Converter"
    | "Exposure"
    | "Shadows"
    | "Brightness"
    | "Smoothness"
    | "MoireFilter";

  export type GenericTag = number | number[] | string | Buffer | null;

  export type ExifTags = Record<ExifTagName, GenericTag> & {
    // override GenericTag based on exif standard tag types https://exiv2.org/tags.html
    ImageWidth: number;
    ImageHeight: number;
    Make: string;
    Model: string;
    Orientation: number;
    ThumbnailOffset: number;
    ThumbnailLength: number;
    ExposureTime: number;
    TimeZoneOffset: number;
    ISOSpeed: number;
    ISOSpeedLatitudeyyy: number;
    ISOSpeedLatitudezzz: number;
    ShutterSpeedValue: number;
    ApertureValue: number;
    BrightnessValue: number;
    ExposureBiasValue: number;
    MaxApertureValue: number;
    SubjectDistance: number;
    LightSource: number;
    Flash: number;
    FocalLength: number;
    SubSecTime: string;
    SubSecTimeOriginal: string;
    SubSecTimeDigitized: string;
    ColorSpace: number;
    PixelXDimension: number;
    PixelYDimension: number;
    ExposureIndex: number;
    SensingMethod: number;
    ExposureMode: number;
    WhiteBalance: number;
    DigitalZoomRatio: number;
    FocalLengthIn35mmFormat: number;
    SceneCaptureType: number;
    GainControl: number;
    Contrast: number;
    Saturation: number;
    Sharpness: number;
    Gamma: number;
    ImageWidth: number;
    ImageHeight: number;
    WidthResolution: number;
    HeightResolution: number;
    FrameRate: number;

    // Offsets
    ExifOffset: number;
    GPSInfo: number;
    InteropOffset: number;

    // the following tags are converted to Date while reading in index.js
    ModifyDate: Date;
    DateTimeOriginal: Date;
    DateTimeDigitized: Date;

    // dynamic tags
    [unknown: string]: GenericTag;
  };

  export type GPSTags = {
    GPSVersionID: GenericTag;
    GPSLatitudeRef: string;
    GPSLatitude: number[];
    GPSLongitudeRef: string;
    GPSLongitude: number[];
    GPSAltitudeRef: number;
    GPSAltitude: number;
    GPSTimeStamp: number[];
    GPSSatellites: string;
    GPSStatus: string;
    GPSMeasureMode: string;
    GPSDOP: number;
    GPSSpeedRef: string;
    GPSSpeed: number;
    GPSTrackRef: string;
    GPSTrack: number;
    GPSImgDirectionRef: string;
    GPSImgDirection: number;
    GPSMapDatum: string;
    GPSDestLatitudeRef: string;
    GPSDestLatitude: number[];
    GPSDestLongitudeRef: string;
    GPSDestLongitude: number[];
    GPSDestBearingRef: string;
    GPSDestBearing: number;
    GPSDestDistanceRef: string;
    GPSDestDistance: string;
    GPSProcessingMethod: Buffer;
    GPSAreaInformation: Buffer;
    GPSDateStamp: string;
    GPSDifferential: number;
    GPSHPositioningError: number;
  };

  export type Exif = {
    bigEndian: boolean;
    image?: Partial<ExifTags>;
    exif?: Partial<ExifTags>;
    gps?: Partial<GPSTags>;
    interoperability?: Partial<ExifTags>;
  };

  export default function exif(buffer: Buffer): Exif;
}
